name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:10.22.0-alpine3.11
      env:
        NARWHAL_ENGINE: rhino
    steps:
    - name: install deps
      run: |
        apk update
        apk add git bash curl zip
        apk --no-cache add openjdk11 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
        echo "::set-env name=CAPP_BUILD::$GITHUB_WORKSPACE/Build"
        echo "::set-env name=NARWHAL_HOME::$HOME/narwhal"
    - uses: actions/checkout@v2
    - name: bootstrap
      run: |
        bash bootstrap.sh --noprompt --directory $NARWHAL_HOME
        echo "::add-path::$NARWHAL_HOME/bin"
    - name: test
      run: jake test
    - name: install
      run: jake install
    - name: genapp
      run: |
        capp gen StarterApp -t Application --noconfig
        echo "::set-env name=APP_LOCATION::$GITHUB_WORKSPACE/StarterApp/"
    - uses: actions/upload-artifact@v2
      with:
        name: StarterApp
        path: ${{ env.APP_LOCATION }}
    - name: zip for nightly
      run: zip -r starter_app StarterApp
    - name: deploy-nightly
      if: github.ref == 'refs/heads/master'
      uses: WebFreak001/deploy-nightly@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/davidsiaw/cappuccino/releases/30086598/assets{?name,label}
        release_id: 30086598
        asset_path: ./starter_app.zip # path to archive to upload
        asset_name: starter_app-$$.zip # name to upload the release as, use $$ to insert date (YYYYMMDD) and 6 letter commit hash
        asset_content_type: application/zip
        max_releases: 7