name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:10.22.0-alpine3.11
      env:
        NARWHAL_ENGINE: rhino
    steps:
    - name: install deps
      run: |
        apk update
        apk add git bash curl zip
        apk --no-cache add openjdk11 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
        echo "::set-env name=CAPP_BUILD::$GITHUB_WORKSPACE/Build"
        echo "::set-env name=NARWHAL_HOME::$HOME/narwhal"
    - uses: actions/checkout@v2
    - name: bootstrap
      run: |
        bash bootstrap.sh --noprompt --directory $NARWHAL_HOME
        echo "::add-path::$NARWHAL_HOME/bin"
    - name: test
      run: jake test
    - name: genapp
      run: |
        capp gen StarterApp -t Application --noconfig
    - uses: actions/upload-artifact@v2
      with:
        name: StarterApp
        path: ${{ env.GITHUB_WORKSPACE }}/StarterApp/
