name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:10.22.0-alpine3.11
    steps:
    - name: install deps
      run: |
        apk update
        apk add git bash
        apk --no-cache add openjdk11 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
    - uses: actions/checkout@v2
    - name: bootstrap
      run: bash bootstrap.sh --noprompt --directory ./narwhal
    - name: test
      run: jake test
    - name: deploy
      run: jake deploy
